{% set name = "causalimpact" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/causalimpact-{{ version }}.tar.gz
  sha256: bd94dd61edae3b23e43e70bbbfbada06e6d2f7fbac292ed1dbcfcb3afcca929a

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - python
    - importlib-metadata
    - pandas
    - numpy
    - statsmodels
    - matplotlib-base
    - pytensor
    - pymc
    - {{ compiler('cxx') }}

test:
  source_files:
    - tests
  imports:
    - causalimpact
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/jamalsenouci/causalimpact
  summary: Python Package for causal inference using Bayesian structural time-series models
  description: |
    This package implements an approach to estimating the causal effect of a designed intervention on a time series.
    Given a response time series (e.g., clicks) and a set of control time series (e.g., clicks in non-affected markets
    or clicks on other sites), the package constructs a Bayesian structural time-series model. This model is then used
    to try and predict the counterfactual, i.e., how the response metric would have evolved after the intervention if
    the intervention had never occurred
  license: Apache-2.0
  license_file: LICENSE.md
  license_family: Apache
  dev_url: https://github.com/jamalsenouci/causalimpact
  doc_url: https://nbviewer.org/github/jamalsenouci/causalimpact/blob/master/GettingStarted.ipynb

extra:
  recipe-maintainers:
    - jamalsenouci
    - nicornk
